[workspace]
resolver = "2"
members = ["contracts/*", "contracts/stellar-upgrader/src/tests/testdata/*", "packages/*"]

[workspace.package]
edition = "2021"
rust-version = "1.93.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
alloy-primitives = { version = "0.8.19", default-features = false }
alloy-sol-types = { version = "0.8.19", default-features = false }
cfg-if = { version = "1.0", default-features = false }
goldie = { version = "0.5.0", default-features = false }
hex = { version = "0.4", default-features = false }
paste = { version = "1.0", default-features = false }
proc-macro2 = { version = "1.0", default-features = false }
rand = { version = "0.8.5", default-features = false }
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
soroban-token-sdk = { version = "25.3.1" }
stellar-axelar-example = { version = "^1.0.11", path = "contracts/stellar-axelar-example" }
stellar-axelar-gas-service = { version = "^2.0.2", path = "contracts/stellar-axelar-gas-service" }
stellar-axelar-gateway = { version = "^2.0.2", path = "contracts/stellar-axelar-gateway" }
stellar-axelar-operators = { version = "^1.1.5", path = "contracts/stellar-axelar-operators" }
stellar-axelar-std = { version = "^2.0.2", path = "packages/stellar-axelar-std", features = ["derive"] }
stellar-axelar-std-derive = { version = "^2.1.1", path = "packages/stellar-axelar-std-derive" }
stellar-interchain-token = { version = "^2.0.2", path = "contracts/stellar-interchain-token" }
stellar-interchain-token-service = { version = "^2.1.2", path = "contracts/stellar-interchain-token-service" }
stellar-multicall = { version = "^1.0.5", path = "contracts/stellar-multicall" }
stellar-strkey = { version = "0.0.9" }
stellar-token-manager = { version = "^1.1.5", path = "contracts/stellar-token-manager" }
stellar-token-utils = { version = "^1.0.3", path = "contracts/stellar-token-utils" }
stellar-upgrader = { version = "^1.1.5", path = "contracts/stellar-upgrader" }

[workspace.lints.clippy]
nursery = { level = "warn", priority = -1 }
too_many_arguments = "allow"
cloned_ref_to_slice_refs = "allow"

[workspace.lints.rust]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
