# This workflow creates a github release using release-plz, and publishes it as a rust crates and also create the necessary artifacts (wasm).

name: Release
on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # Publishes a release in case the release isn't published
  publish-release:
    name: Publish releases

    runs-on: blacksmith-2vcpu-ubuntu-2204

    outputs:
      releases: ${{ steps.prepare-matrix.outputs.releases }}
      commit_hash: ${{ steps.get-commit-hash.outputs.hash }}

    steps:
      - name: Generate GitHub token
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.89.0

      - name: Get commit hash
        id: get-commit-hash
        run: echo "hash=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Dry Run
        id: dry-run
        uses: release-plz/action@v0.5
        with:
          command: release --dry-run
          version: "0.3.157"
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish release
        id: publish-release
        uses: release-plz/action@v0.5
        with:
          command: release
          version: "0.3.157"
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Prepare JSON output to be a matrix GHA format
        id: prepare-matrix
        run: |
          if [ "${{ steps.publish-release.outputs.releases }}" == "[]" ]; then
            echo "release-plz output contains an empty release list — exiting early."
            exit 1
          fi

          echo "releases=$(echo '${{ steps.publish-release.outputs.releases }}' | jq -c '.')" >> $GITHUB_OUTPUT

  build:
    needs: publish-release
    uses: ./.github/workflows/reusable-build.yaml
    with:
      commit-hash: ${{ needs.publish-release.outputs.commit_hash }}

  upload:
    needs: [publish-release, build]
    strategy:
      matrix:
        releases: ${{ fromJson(needs.publish-release.outputs.releases) }}

    uses: ./.github/workflows/reusable-upload.yaml
    permissions:
      id-token: write
      contents: read
    with:
      package-name: ${{ matrix.releases.package_name }}
      package-version: ${{ matrix.releases.version }}
      package-git-tag: ${{ matrix.releases.tag }}
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      artifact-path: ${{ needs.build.outputs.artifact-path }}
      cf-bucket-name: ${{ vars.CF_BUCKET_NAME }}
      cf-config-bucket-root-key: ${{ vars.CF_BUCKET_ROOT_KEY }}
      github-release: true
    secrets:
      bot-app-id: ${{ secrets.BOT_APP_ID }}
      bot-app-private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      cf-endpoint-url: ${{ secrets.CF_ENDPOINT_URL }}
      cf-bucket-access-key-id: ${{ secrets.CF_BUCKET_ACCESS_KEY_ID }}
      cf-bucket-secret-access-key: ${{ secrets.CF_BUCKET_SECRET_ACCESS_KEY }}
