# This workflow performs a dry-run release using release-plz

name: Dry-Run Release

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  dry-run-release:
    name: Dry-Run Release

    runs-on: blacksmith-2vcpu-ubuntu-2204

    outputs:
      releases: ${{ steps.prepare-matrix.outputs.releases }}
      commit_hash: ${{ steps.get-commit-hash.outputs.hash }}

    steps:
      - name: Generate GitHub token
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.89.0

      - name: Get commit hash
        id: get-commit-hash
        run: echo "hash=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Dry-run
        id: dry-run
        uses: release-plz/action@v0.5
        with:
          command: release --dry-run
          version: "0.3.157"
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
